# Generated by Django 5.0.1 on 2024-03-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nacimientosBebes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('hora_nacimiento', models.TimeField(null=True)),
                ('lugar_nacimiento', models.CharField(max_length=100, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nombre_padre', models.CharField(max_length=100, null=True)),
                ('nombre_madre', models.CharField(max_length=100, null=True)),
                ('telefono_contacto', models.CharField(max_length=20, null=True)),
                ('email_contacto', models.EmailField(max_length=254, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('tipo_nacimiento', models.CharField(choices=[('normal', 'Normal'), ('cesarea', 'Cesárea')], max_length=8, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(null=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('presion_arterial_sistolica', models.IntegerField(null=True)),
                ('presion_arterial_diastolica', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='nacimientos_bebes',
        ),
        migrations.DeleteModel(
            name='seguimiento_pediatria',
        ),
        migrations.CreateModel(
            name='SeguimientoPediatrico',
            fields=[
                ('id_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.nacimientosbebes')),
                ('cita_id', models.IntegerField(null=True)),
                ('fecha_seguimiento', models.DateField(null=True)),
                ('edad_anios', models.IntegerField(null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('perimetro_cranial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(null=True)),
                ('frecuencia_cardiaca', models.IntegerField(null=True)),
                ('presion_arterial_sistolica', models.IntegerField(null=True)),
                ('presion_arterial_diastolica', models.IntegerField(null=True)),
                ('vacunas_administradas', models.TextField(null=True)),
                ('examenes_medicos_realizados', models.TextField(null=True)),
                ('observaciones', models.TextField(null=True)),
            ],
        ),
    ]
