# Generated by Django 5.0.1 on 2024-03-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nacimientosbebes_delete_nacimientos_bebes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AprobacionesServicios',
        ),
        migrations.DeleteModel(
            name='BitacoraDG',
        ),
        migrations.DeleteModel(
            name='c_cirugia',
        ),
        migrations.DeleteModel(
            name='c_cliente',
        ),
        migrations.DeleteModel(
            name='c_dispensacion',
        ),
        migrations.DeleteModel(
            name='c_estudio',
        ),
        migrations.DeleteModel(
            name='c_inventario',
        ),
        migrations.DeleteModel(
            name='c_receta_medica',
        ),
        migrations.DeleteModel(
            name='c_receta_medica_detalles',
        ),
        migrations.DeleteModel(
            name='c_registrosM',
        ),
        migrations.DeleteModel(
            name='c_rol',
        ),
        migrations.DeleteModel(
            name='c_Solicitud_Cirugias',
        ),
        migrations.RemoveField(
            model_name='resultadoestudio',
            name='cita',
        ),
        migrations.DeleteModel(
            name='Consumible',
        ),
        migrations.RemoveField(
            model_name='resultadoestudio',
            name='estudio',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
        migrations.DeleteModel(
            name='ServiciosHospitalarios',
        ),
        migrations.DeleteModel(
            name='ServiciosMedicos',
        ),
        migrations.DeleteModel(
            name='solicitud_organos_1',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='ResultadoEstudio',
        ),
    ]
