# Generated by Django 5.0.1 on 2024-04-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_aprobacionesservicios_delete_bitacoradg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacimientosbebes',
            name='sexo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
