# Generated by Django 5.0.1 on 2024-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_nacimientosbebes_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguimientoPediatrico',
        ),
    ]
