# Generated by Django 4.1.13 on 2024-04-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_seguimientopediatrico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewNacimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('hora_nacimiento', models.TimeField()),
                ('tipo_de_nacimiento', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
