# Generated by Django 4.1.13 on 2024-04-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_viewnacimientos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewNacimientos',
        ),
    ]
