# Generated by Django 5.0.4 on 2024-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_viewnacimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewNacimientosCiudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lugar_nacimiento', models.CharField(max_length=100, null=True)),
                ('cantidad_nacimientos', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vw_nacimientos_por_ciudad',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='nacimientosbebes',
            name='tipo_nacimiento',
            field=models.CharField(choices=[('normal', 'Normal'), ('cesarea', 'Cesarea')], max_length=8, null=True),
        ),
    ]
