# Generated by Django 5.0.4 on 2024-04-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_viewnacimientosciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacimientosbebes',
            name='tipo_nacimiento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
